### ISSUE TITLE
Replicator/lib fails (in inifnite loop) when there are too many generations

### ISSUE THREAD

**Issue by avelanarius** [haaawk/scylla-cdc-java#2]
When there are too many generations (in my case about 9-12 - enough to trigger pagination), replicator fails with this exception (repeated in endless loop):

```
java.lang.IllegalStateException: Detected a synchronous call on an I/O thread, this can cause deadlocks or unpredictable behavior. This generally happens when a Future callback calls a synchronous Session method (execute() or prepare()), or iterates a result set past the fetch size (causing an internal synchronous fetch of the next page of results). Avoid this in your callbacks, or schedule them on a different executor.
	at com.datastax.driver.core.AbstractSession.checkNotInEventLoop(AbstractSession.java:185)
	at com.datastax.driver.core.ArrayBackedResultSet$MultiPage.prepareNextRow(ArrayBackedResultSet.java:368)
	at com.datastax.driver.core.ArrayBackedResultSet$MultiPage.isExhausted(ArrayBackedResultSet.java:326)
	at com.scylladb.cdc.driver.Reader.consumeResults(Reader.java:72)
	at com.scylladb.cdc.driver.Reader.consumeResults(Reader.java:85)
	at com.scylladb.cdc.driver.Reader.lambda$query$4(Reader.java:90)
	at com.scylladb.cdc.common.FutureUtils$3.onSuccess(FutureUtils.java:70)
	at com.google.common.util.concurrent.Futures$6.run(Futures.java:1773)
	at com.google.com^Cmon.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:456)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:817)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:753)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:613)
	at com.datastax.driver.core.DefaultResultSetFuture.onSet(DefaultResultSetFuture.java:210)
	at com.datastax.driver.core.RequestHandler.setFinalResult(RequestHandler.java:229)
	at com.datastax.driver.core.RequestHandler.access$2600(RequestHandler.java:63)
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.setFinalResult(RequestHandler.java:1011)
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onSet(RequestHandler.java:648)
	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1289)
	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1207)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:312)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at com.datastax.driver.core.InboundTrafficMeter.channelRead(InboundTrafficMeter.java:38)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1304)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:921)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:135)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:646)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

The issue occurs at line (`Reader` when used by `GenerationsFetcher`):

https://github.com/haaawk/scylla-cdc-java/blob/5edc5fe016285c7bb362cd40f7c352f66bff8e4c/scylla-cdc-lib/src/main/java/com/scylladb/cdc/driver/Reader.java#L72

`isExhausted` calls internally `prepareNextRow`:

https://github.com/scylladb/java-driver/blob/f3ee452ae7547acc79c53cfbd45fd3bcf1705800/driver-core/src/main/java/com/datastax/driver/core/ArrayBackedResultSet.java#L326

and `prepareNextRow` fails at line:

https://github.com/scylladb/java-driver/blob/f3ee452ae7547acc79c53cfbd45fd3bcf1705800/driver-core/src/main/java/com/datastax/driver/core/ArrayBackedResultSet.java#L368

**Comment by haaawk** [comment]
I've seen this before in other context so the fix shouldn't be difficult. Thanks for reporting.
